apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  namespace: production
spec:
  selector:
    matchLabels:
      app: classifier
  replicas: 1
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
      - image: openstatefoundation/ori-theme-classifier:v1.0.0
        name: classifier
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 50M
            cpu: 80m
      restartPolicy: Always
