version: "2.1"

services:

    frontend:
        build: 'ocd_frontend'
        volumes:
            - ./ocd_frontend:/opt/ori/ocd_frontend
        command: python wsgi.py
        ports:
            - "127.0.0.1:5000:5000"

    redis:
        image: 'redis'
        volumes:
         - redisdata:/data
        sysctls:
         - net.core.somaxconn=65535
        mem_limit: 2g
        ports:
            - "127.0.0.1:6379:6379"

    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}"
        environment:
            - network.host=0.0.0.0
            - http.host=0.0.0.0
            - node.master=true
            - xpack.security.enabled=false
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - "127.0.0.1:9200:9200"

volumes:
    esdata:
        driver: local
    redisdata:
        driver: local
